/* eslint-disable @typescript-eslint/camelcase */

import m_0 from '../../../public/img/monsters/m_0.svg';
import m_1 from '../../../public/img/monsters/m_1.svg';
import m_10 from '../../../public/img/monsters/m_10.svg';
import m_11 from '../../../public/img/monsters/m_11.svg';
import m_12 from '../../../public/img/monsters/m_12.svg';
import m_13 from '../../../public/img/monsters/m_13.svg';
import m_14 from '../../../public/img/monsters/m_14.svg';
import m_15 from '../../../public/img/monsters/m_15.svg';
import m_16 from '../../../public/img/monsters/m_16.svg';
import m_17 from '../../../public/img/monsters/m_17.svg';
import m_18 from '../../../public/img/monsters/m_18.svg';
import m_19 from '../../../public/img/monsters/m_19.svg';
import m_2 from '../../../public/img/monsters/m_2.svg';
import m_20 from '../../../public/img/monsters/m_20.svg';
import m_21 from '../../../public/img/monsters/m_21.svg';
import m_22 from '../../../public/img/monsters/m_22.svg';
import m_23 from '../../../public/img/monsters/m_23.svg';
import m_24 from '../../../public/img/monsters/m_24.svg';
import m_3 from '../../../public/img/monsters/m_3.svg';
import m_4 from '../../../public/img/monsters/m_4.svg';
import m_5 from '../../../public/img/monsters/m_5.svg';
import m_6 from '../../../public/img/monsters/m_6.svg';
import m_7 from '../../../public/img/monsters/m_7.svg';
import m_8 from '../../../public/img/monsters/m_8.svg';
import m_9 from '../../../public/img/monsters/m_9.svg';
export { m_0,m_1,m_10,m_11,m_12,m_13,m_14,m_15,m_16,m_17,m_18,m_19,m_2,m_20,m_21,m_22,m_23,m_24,m_3,m_4,m_5,m_6,m_7,m_8,m_9 }